name: 'TribalMedicine'
main: net.inizicraft.TribalMedicine.TribalMain
description: 'A set of items for Inizicraft'
version: 0.0.1
api-version: 1.13
load: STARTUP
author: [StarBound]
commands:
  tm:
    description: TribalMedicine
    usage: /<command>